### PR TITLE
Added simple display option buttons to switch between input, output, …

### PR DESCRIPTION
**Pull request by thurt**
…or both

### CODE REVIEW

**Comment by thurt** [comment]
ramda/ramda#1752

Demo: http://rawgit.com/thurt/ramtuary/display-options/index.html

I initially thought a horizontal resize bar would be nice but implementing this with Bootstrap so that it works with dynamic screen resize looks like it might be a pain.

I think these display buttons are a simple alternative.
What do you think?

**Comment by davidchase** [comment]
@thurt looks great... did you want to PR this over at https://github.com/ramda/ramda.github.io/tree/master/repl << thats where the repl is housed 

I am currently moving over to a larger input/output view, adding more functional libraries such as [daggy](https://github.com/puffnfresh/daggy) and switching to [buble](https://gitlab.com/Rich-Harris/buble) for speed and for fun 😄 

that being said i would definitely like something like this on my repo as well... but if you want it to be on the ramda repl... check out the link ☝️

**Comment by thurt** [comment]
@davidchase 
Maybe it would make sense to treat ramtuary as an upstream version of the official ramda repl?
I think this makes sense so features aren't duplicated in two different repos. 

However, this may depend on how "ramda specific" you intend to be. Ramda people may not want other functional libraries in their repl. It would be nice if there was some easy way to define default libraries to load into the repl so different parties could setup the repl as they like it.

> buble for speed and for fun

Bublé sounds interesting. I did notice the inclusion of babel in ramtuary adds significant download size--it would be a great improvement if there was something faster/smaller for the browser.

> I am currently moving over to a larger input/output view

I know I would also like to see larger display or fullscreen option. 
I tried the CodeMirror fullscreen.js/.css add-on which works fine. Except there are some CSS issues that would need to be worked out for displaying both input and output with scrolling while in fullscreen.

**Comment by davidchase** [comment]
> However, this may depend on how "ramda specific" you intend to be. Ramda people may not want other functional libraries in their repl.

ramtuary was really just a experiment that went well and became the new ramda repl, i actually make/made updates to the ramda repl directly at their github repo.

as for ramtuary i still just want it to be an experimental playground where i can test out ideas such as buble and adding different libraries... i mean really there are so many repls/bins out there like jsbin/jsfiddle/webpackbin

> Maybe it would make sense to treat ramtuary as an upstream version of the official ramda repl?

yeah thats not a bad idea either... but since the ramda repl has been updated i didnt think many people still used my version

**Comment by thurt** [comment]
Thanks for the background info -- I wasn't aware how the repl came to be.

> i didnt think many people still used my version

I think tab auto-completion is great but it doesn't work in the ramda repl ? 

I agree about the "so many repls/bins already out there." 
However, this repl style is still very important as part of on-boarding for new users because it is _zero_ setup and _zero_ commitment. Existing users may also use that repl as "scratch" space.

In that respect, I still think the ramda repl needs a few things: autocomplete, larger viewing area/fullscreen, and an "about" modal which has a few sentences about the pre-loaded libraries, Ramda + Ramda Fantasy + Sanctuary.

**Comment by thurt** [comment]
Closing this PR. I will direct PRs to ramda repl in ramda/ramda.github.io as suggested. 
@davidchase feel free to copy/merge this PR if you think it is useful for your work!

**Comment by thurt** [comment]
p.s. I see now that the ramda repl actually does have autocomplete. It is just not prefixed with `R.`

**Pull request closed without merging**
